Repository TheRealKasumi/NikoLight, pull requests merged in 2023-03, with the labels that each got.

#150 fix(profiles): invalidate cache after profile switch
  ui/src/pages/Profiles.tsx
  ui/src/pages/Update.tsx
  ui/src/pages/api/fseq.ts
  ui/src/pages/api/index.ts
  ui/src/pages/api/led.ts
  ui/src/pages/api/log.ts
  ui/src/pages/api/profile.ts
  ui/src/pages/api/system.ts
  ui/src/pages/api/systemInfo.ts
  ui/src/pages/api/ui.ts
  ui/src/pages/api/update.ts
  ui/src/pages/api/wifi.ts
Labels: bug, frontend

#152 feat: add new pulse effect
  documentation/api/ReadMe.md
  mcu/include/configuration/SystemConfiguration.h
  mcu/include/led/LedManager.h
  mcu/include/led/animator/PulseAnimator.h
  mcu/include/update/TupFile.h
  mcu/src/SystemInformation.cpp
  mcu/src/TesLight.cpp
  mcu/src/configuration/Configuration.cpp
  mcu/src/led/LedManager.cpp
  mcu/src/led/animator/PulseAnimator.cpp
  mcu/src/led/driver/Pixel.cpp
  mcu/src/server/LedConfigurationEndpoint.cpp
  mcu/src/server/SystemConfigurationEndpoint.cpp
  mcu/src/server/UpdateEndpoint.cpp
  mcu/src/update/TupFile.cpp
  mcu/src/update/Updater.cpp
  ui/public/locales/de/translation.json
  ui/public/locales/en/translation.json
  ui/src/components/Animation.tsx
  ui/src/pages/Zone.tsx
Labels: enhancement, mcu

#153 chore(ui): update dependencies
  ui/package-lock.json
  ui/package.json
  ui/pnpm-lock.yaml
Labels: dependencies

#165 chore(ui): update dependencies
  ui/package.json
  ui/pnpm-lock.yaml
Labels: frontend, dependencies

#164 feat: add new EQ effect
  documentation/api/ReadMe.md
  mcu/include/led/LedManager.h
  mcu/include/led/animator/EqualizerAnimator.h
  mcu/src/hardware/DS18B20.cpp
  mcu/src/led/LedManager.cpp
  mcu/src/led/animator/EqualizerAnimator.cpp
  mcu/src/led/animator/GradientAnimator.cpp
  mcu/src/led/animator/GradientAnimatorMotion.cpp
  mcu/src/server/LedConfigurationEndpoint.cpp
  ui/public/locales/de/translation.json
  ui/public/locales/en/translation.json
  ui/src/components/Animation.tsx
  ui/src/pages/Zone.tsx
Labels: documentation, enhancement, frontend, mcu

#169 proposal: cleaner table style
  ReadMe.md
Labels: documentation

#166 Feat/132 add contributors
  ReadMe.md
Labels: documentation

#170 Otherwise bad things can happen in some situations....
  mcu/src/wifi/WiFiManager.cpp
Labels: bug, mcu

#171 chore(ui): update dependencies
  ui/package-lock.json
  ui/package.json
  ui/pnpm-lock.yaml
Labels: frontend, dependencies

#172 feat(motion): add auto motion sensor calibration to ui
  ui/package-lock.json
  ui/package.json
  ui/pnpm-lock.yaml
  ui/public/locales/de/translation.json
  ui/public/locales/en/translation.json
  ui/src/components/AlertDialog.tsx
  ui/src/components/Button.tsx
  ui/src/components/Collapsible.tsx
  ui/src/components/Toast.tsx
  ui/src/components/index.tsx
  ui/src/mocks/handlers.ts
  ui/src/pages/Settings.tsx
  ui/src/pages/api/index.ts
  ui/src/pages/api/motionSensorCalibration.ts
Labels: enhancement, frontend
