Repository TheRealKasumi/NikoLight, pull requests merged in 2023-01, with the labels that each got.

#88 Documentation Build Guide: Reflect renaming of web-app to ui, #87
  documentation/build.md
Labels: documentation

#93 feat (animation) add the new sparkele animator
  documentation/api/OpenApi.yaml
  documentation/api/ReadMe.md
  documentation/api/TesLight API.postman_collection.json
  mcu/include/configuration/Configuration.h
  mcu/include/configuration/SystemConfiguration.h
  mcu/include/led/LedManager.h
  mcu/include/led/animator/ColorBarAnimator.h
  mcu/include/led/animator/FseqAnimator.h
  mcu/include/led/animator/GradientAnimator.h
  mcu/include/led/animator/GradientAnimatorMotion.h
  mcu/include/led/animator/LedAnimator.h
  mcu/include/led/animator/RainbowAnimator.h
  mcu/include/led/animator/RainbowAnimatorMotion.h
  mcu/include/led/animator/SparkleAnimator.h
  mcu/include/led/animator/StaticColorAnimator.h
  mcu/include/sensor/MotionSensor.h
  mcu/include/server/LedConfigurationEndpoint.h
  mcu/platformio.ini
  mcu/src/configuration/Configuration.cpp
  mcu/src/led/LedManager.cpp
  mcu/src/led/animator/ColorBarAnimator.cpp
  mcu/src/led/animator/FseqAnimator.cpp
  mcu/src/led/animator/GradientAnimator.cpp
  mcu/src/led/animator/GradientAnimatorMotion.cpp
  mcu/src/led/animator/LedAnimator.cpp
  mcu/src/led/animator/RainbowAnimator.cpp
  mcu/src/led/animator/RainbowAnimatorMotion.cpp
  mcu/src/led/animator/SparkleAnimator.cpp
  mcu/src/led/animator/StaticColorAnimator.cpp
  mcu/src/server/FseqEndpoint.cpp
  mcu/src/server/LedConfigurationEndpoint.cpp
Labels: documentation, mcu

#94 feat(ui): add new animations
  ui/package-lock.json
  ui/package.json
  ui/pnpm-lock.yaml
  ui/public/locales/de/translation.json
  ui/public/locales/en/translation.json
  ui/src/components/Animation.tsx
  ui/src/components/Collapsible.tsx
  ui/src/components/Select.tsx
  ui/src/components/Toast.tsx
  ui/src/components/index.tsx
  ui/src/mocks/handlers.ts
  ui/src/pages/CustomAnimations.tsx
  ui/src/pages/Home.tsx
  ui/src/pages/Settings.tsx
  ui/src/pages/Zone.tsx
  ui/src/pages/api/led.ts
  ui/src/pages/api/openapi.json
Labels: frontend

#97 fix(ui): units for automatic brightness
  ui/src/pages/Settings.tsx
  ui/src/pages/Update.tsx
  ui/src/pages/Zone.tsx
Labels: enhancement, frontend

#101 fix(ui): wifi configuration
  ui/src/pages/CustomAnimations.tsx
  ui/src/pages/Settings.tsx
  ui/src/pages/Update.tsx
  ui/src/pages/Zone.tsx
Labels: bug, frontend

#108 fix(ui): update wifi config only if there was a change
  ui/src/pages/Settings.tsx
  ui/src/pages/Zone.tsx
Labels: frontend

#112 refactor(ui): update translations
  ui/public/locales/de/translation.json
  ui/public/locales/en/translation.json
  ui/src/pages/Settings.tsx
Labels: frontend

#115 feat(ui): add light theme
  ui/public/locales/de/translation.json
  ui/public/locales/en/translation.json
  ui/src/App.tsx
  ui/src/assets/center-console.svg
  ui/src/assets/dashboard.svg
  ui/src/assets/door.svg
  ui/src/assets/footwell-left.svg
  ui/src/assets/footwell-right.svg
  ui/src/components/Button.tsx
  ui/src/components/InputPassword.tsx
  ui/src/components/InputText.tsx
  ui/src/components/InputType.tsx
  ui/src/components/Log.tsx
  ui/src/components/Select.tsx
  ui/src/components/Slider.tsx
  ui/src/components/Switch.tsx
  ui/src/components/Toast.tsx
  ui/src/libs/index.ts
  ui/src/libs/theme.ts
  ui/src/pages/Home.tsx
  ui/src/pages/Settings.tsx
  ui/tailwind.config.cjs
Labels: frontend

#116 feat(ui): add expert mode
  ui/public/locales/de/translation.json
  ui/public/locales/en/translation.json
  ui/src/assets/swagger.svg
  ui/src/pages/Home.tsx
  ui/src/pages/Settings.tsx
Labels: frontend

#113 feat (fan) add multiple fan mode
  documentation/api/OpenApi.yaml
  documentation/api/TesLight API.postman_collection.json
  mcu/include/TesLight.h
  mcu/include/configuration/Configuration.h
  mcu/include/configuration/SystemConfiguration.h
  mcu/include/hardware/AnalogInput.h
  mcu/include/hardware/Fan.h
  mcu/src/TesLight.cpp
  mcu/src/configuration/Configuration.cpp
  mcu/src/hardware/Fan.cpp
  mcu/src/hardware/FanController.cpp
  mcu/src/server/SystemConfigurationEndpoint.cpp
  ui/src/pages/api/openapi.json
Labels: documentation, enhancement, mcu

#117 feat(ui): add fan mode
  ui/public/locales/de/translation.json
  ui/public/locales/en/translation.json
  ui/src/mocks/handlers.ts
  ui/src/pages/Settings.tsx
  ui/src/pages/api/openapi.json
  ui/src/pages/api/system.ts
Labels: frontend

#118 feat (audio) add audio unit
  documentation/api/OpenApi.yaml
  documentation/api/TesLight API.postman_collection.json
  mcu/include/TesLight.h
  mcu/include/configuration/Configuration.h
  mcu/include/configuration/SystemConfiguration.h
  mcu/include/hardware/AudioUnit.h
  mcu/include/led/LedManager.h
  mcu/include/led/animator/LedAnimator.h
  mcu/include/server/AudioUnitConfigurationEndpoint.h
  mcu/src/TesLight.cpp
  mcu/src/configuration/Configuration.cpp
  mcu/src/hardware/AudioUnit.cpp
  mcu/src/led/LedManager.cpp
  mcu/src/led/animator/LedAnimator.cpp
  mcu/src/server/AudioUnitConfigurationEndpoint.cpp
  mcu/src/server/FseqEndpoint.cpp
  mcu/src/server/LedConfigurationEndpoint.cpp
  mcu/src/server/LogEndpoint.cpp
  mcu/src/server/MotionSensorEndpoint.cpp
  mcu/src/server/SystemConfigurationEndpoint.cpp
  mcu/src/server/SystemInformationEndpoint.cpp
  mcu/src/server/UIConfigurationEndpoint.cpp
  mcu/src/server/WiFiConfigurationEndpoint.cpp
  ui/src/pages/api/openapi.json
Labels: documentation, enhancement, hardware, mcu

#120 feat (sparkle) bounce particles
  documentation/api/ReadMe.md
  mcu/include/led/animator/SparkleAnimator.h
  mcu/platformio.ini
  mcu/src/led/LedManager.cpp
  mcu/src/led/animator/SparkleAnimator.cpp
  mcu/src/util/WatchDog.cpp
Labels: enhancement, mcu

#119 feat(ui): show only available hardware based options
  ui/public/locales/de/translation.json
  ui/public/locales/en/translation.json
  ui/src/components/Notification.tsx
  ui/src/components/Slider.tsx
  ui/src/mocks/handlers.ts
  ui/src/pages/CustomAnimations.tsx
  ui/src/pages/Settings.tsx
  ui/src/pages/Update.tsx
  ui/src/pages/Zone.tsx
  ui/src/pages/api/index.ts
  ui/src/pages/api/systemInfo.ts
Labels: frontend

#124 feat(ui): add bounce option for particles
  ui/public/locales/de/translation.json
  ui/public/locales/en/translation.json
  ui/src/pages/Zone.tsx
Labels: frontend

#130 fix locale on Mac
  update-package-tool/.vscode/tasks.json
  update-package-tool/ReadMe.md
  update-package-tool/src/main.cpp
Labels: bug, documentation, enhancement

#133 feat(ui): add dataSource property and audio based sparkle effect
  ui/package-lock.json
  ui/package.json
  ui/pnpm-lock.yaml
  ui/public/locales/de/translation.json
  ui/public/locales/en/translation.json
  ui/src/components/Animation.tsx
  ui/src/components/Select.tsx
  ui/src/components/ToggleGroup.tsx
  ui/src/components/index.tsx
  ui/src/mocks/handlers.ts
  ui/src/pages/Settings.tsx
  ui/src/pages/Zone.tsx
  ui/src/pages/api/led.ts
  ui/src/pages/api/openapi.json
Labels: frontend

#126 feat (audio) audio based sparkle
  documentation/api/OpenApi.yaml
  documentation/api/ReadMe.md
  documentation/api/TesLight API.postman_collection.json
  mcu/include/configuration/Configuration.h
  mcu/include/configuration/SystemConfiguration.h
  mcu/include/hardware/AudioUnit.h
  mcu/include/hardware/BH1750.h
  mcu/include/hardware/DS18B20.h
  mcu/include/hardware/Fan.h
  mcu/include/hardware/MPU6050.h
  mcu/include/led/animator/ColorBarAnimator.h
  mcu/include/led/animator/GradientAnimator.h
  mcu/include/led/animator/GradientAnimatorMotion.h
  mcu/include/led/animator/LedAnimator.h
  mcu/include/led/animator/RainbowAnimator.h
  mcu/include/led/animator/RainbowAnimatorMotion.h
  mcu/include/led/animator/SparkleAnimator.h
  mcu/include/logging/Logger.h
  mcu/include/sensor/LightSensor.h
  mcu/include/sensor/MotionSensor.h
  mcu/include/server/LedConfigurationEndpoint.h
  mcu/include/update/TupFile.h
  mcu/src/TesLight.cpp
  mcu/src/configuration/Configuration.cpp
  mcu/src/hardware/BH1750.cpp
  mcu/src/hardware/DS18B20.cpp
  mcu/src/hardware/MPU6050.cpp
  mcu/src/led/LedManager.cpp
  mcu/src/led/animator/ColorBarAnimator.cpp
  mcu/src/led/animator/FseqAnimator.cpp
  mcu/src/led/animator/GradientAnimator.cpp
  mcu/src/led/animator/GradientAnimatorMotion.cpp
  mcu/src/led/animator/LedAnimator.cpp
  mcu/src/led/animator/RainbowAnimatorMotion.cpp
  mcu/src/led/animator/SparkleAnimator.cpp
  mcu/src/server/LedConfigurationEndpoint.cpp
  mcu/src/server/WiFiConfigurationEndpoint.cpp
  mcu/src/update/TupFile.cpp
Labels: documentation, enhancement, mcu
