Repository TheRealKasumi/NikoLight, pull requests merged in 2023-02, with the labels that each got.

#139 feat(ui): add color switch
  ui/public/locales/de/translation.json
  ui/public/locales/en/translation.json
  ui/src/pages/Zone.tsx
Labels: frontend

#143 fix (bh1750) invert light sensor
  mcu/src/TesLight.cpp
  mcu/src/hardware/BH1750.cpp
  mcu/src/sensor/LightSensor.cpp
Labels: bug, mcu

#146 chore(ui): update dependencies
  ui/package-lock.json
  ui/package.json
  ui/pnpm-lock.yaml
  ui/public/mockServiceWorker.js
  ui/src/App.tsx
  ui/src/pages/Home.tsx
  ui/src/pages/Zone.tsx
  ui/src/react-router.d.ts
Labels: frontend

#148 feat(profiles): add profiles to ui
  ui/public/locales/de/translation.json
  ui/public/locales/en/translation.json
  ui/src/App.tsx
  ui/src/components/Button.tsx
  ui/src/mocks/handlers.ts
  ui/src/pages/CustomAnimations.tsx
  ui/src/pages/Profiles.tsx
  ui/src/pages/Update.tsx
  ui/src/pages/api/index.ts
  ui/src/pages/api/openapi.json
  ui/src/pages/api/profile.ts
  ui/src/pages/index.tsx
Labels: frontend

#135 DevOps recharged
  .github/actions/get-correct-short-commit-sha/action.yml
  .github/actions/platformio-build/action.yml
  .github/actions/ui-build/action.yml
  .github/actions/ui-lint/action.yml
  .github/actions/update-tool-build/action.yml
  .github/workflows/PlatformIO-Build.yml
  .github/workflows/teslight-update-packaging-tool-and-tup-file-build.yml
  .github/workflows/ui-build.yml
  .github/workflows/ui.yml
  ReadMe.md
  update-package-tool/ReadMe.md
Labels: enhancement

#149 chore(ui): update dependencies
  ui/package-lock.json
  ui/package.json
  ui/pnpm-lock.yaml
  ui/public/mockServiceWorker.js
Labels: frontend
